version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: composer require phpunit/phpunit:^5.0.0
  test:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: composer require phpunit/phpunit:^5.0.0 && ./vendor/bin/phpunit --log-junit ./test-results/junit/junit.xml
      - store_test_results:
          path: test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
