version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.4
    steps:
      - checkout
      - run: composer install
  test:
    docker:
      - image: circleci/php:7.1.4
    steps:
      - checkout
      - run: composer install && ./vendor/bin/phpunit
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
