version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: composer global require phpunit/phpunit
  test:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: composer global require phpunit/phpunit && phpunit
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
